type NavItem = {
  href: string;
  label: string;
};

export type CruiseLine = {
  slug: string;
  name: string;
  offersHref: string;
  bookingHref?: string | null;
  logoSrc: string;
  logoAlt: string;
  logoClassName: string;
  imageSrc: string;
  imageAlt: string;
  detailImageSrc: string;
  detailImageAlt: string;
  description: string;
  descriptionParagraphs: readonly string[];
  ships: readonly string[];
  destinations: readonly string[];
};

export const primaryNav: readonly NavItem[] = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About Us" },
  { href: "/cruise-lines", label: "Cruise Lines" },
  { href: "/faq", label: "FAQ" },
  { href: "/eligibility", label: "Eligibility" },
] as const;

export const headerNav: readonly NavItem[] = [];

export const legalNav: readonly NavItem[] = [
  { href: "/terms-and-conditions", label: "Terms & Conditions" },
  { href: "/privacy-policy", label: "Privacy Policy" },
] as const;

export const cruiseLines: readonly CruiseLine[] = [
  {
    slug: "norwegian-cruise-line",
    name: "Norwegian Cruise Line",
    offersHref: "https://thecruisenews.com/cruises/norwegian-cruise-line/",
    logoSrc: "/assets/logos/partner-cruise-lines/norwegian-cruise-line.png",
    logoAlt: "Norwegian Cruise Line logo",
    logoClassName: "w-[8.2rem] sm:w-[8.95rem]",
    imageSrc: "/assets/images/cruise-lines/norwegian-cruise-line.jpg",
    imageAlt: "Norwegian Luna at sea",
    detailImageSrc: "/assets/images/cruise-lines/norwegian-cruise-line-detail.jpg",
    detailImageAlt: "Norwegian Joy at sea",
    description:
      'Norwegian Cruise Line pioneered "Freestyle Cruising" in 2000, revolutionising the industry by eliminating fixed dining times, assigned seating, and strict dress codes to create a more relaxed, flexible resort-style experience. The line appeals to younger couples, families, and groups who value choice in dining, entertainment, and pacing, delivered on large, amenity-packed ships with a cosmopolitan vibe.',
    descriptionParagraphs: [
      'Norwegian Cruise Line pioneered "Freestyle Cruising" in 2000, revolutionising the industry by eliminating fixed dining times, assigned seating, and strict dress codes to create a more relaxed, flexible resort-style experience. The line appeals to younger couples, families, and groups who value choice in dining, entertainment, and pacing, delivered on large, amenity-packed ships with a cosmopolitan vibe.',
      'The brand stands out for its extensive specialty dining (often 10+ venues per ship), high-energy entertainment including Broadway shows, and innovative top-deck attractions like go-kart tracks and laser tag on newer vessels. Norwegian’s "The Haven" offers a ship-within-a-ship luxury enclave for suite guests, blending mainstream accessibility with premium exclusivity. Recent Prima Class ships emphasise ocean views, outdoor promenades, and wellness-focused design.',
      "Operations span the globe with year-round Caribbean sailings, strong Alaska and Europe summer seasons, and unique Hawaii inter-island cruises on the US-flagged Pride of America. The onboard culture is upbeat and unstructured, with late-night venues, diverse bars, and a tech-forward app for reservations and planning.",
    ],
    ships: [
      "Norwegian Aqua",
      "Norwegian Aura",
      "Norwegian Bliss",
      "Norwegian Breakaway",
      "Norwegian Dawn",
      "Norwegian Encore",
      "Norwegian Epic",
      "Norwegian Escape",
      "Norwegian Gem",
      "Norwegian Getaway",
      "Norwegian Jade",
      "Norwegian Jewel",
      "Norwegian Joy",
      "Norwegian Luna",
      "Norwegian Pearl",
      "Norwegian Prima",
      "Norwegian Sky",
      "Norwegian Spirit",
      "Norwegian Star",
      "Norwegian Sun",
      "Norwegian Viva",
      "Pride of America",
    ],
    destinations: [
      "Africa",
      "Alaska",
      "Asia and Asia Pacific",
      "Australia",
      "Australia/New Zealand",
      "Bahamas",
      "Baltic Sea (Europe)",
      "Bermuda",
      "British Isles",
      "Canada / New England",
      "Canary Islands",
      "Caribbean",
      "Caribbean Eastern",
      "Caribbean Southern",
      "Caribbean Western",
      "Eastern Mediterranean",
      "Europe",
      "Hawaii",
      "Iceland",
      "Japan",
      "Mediterranean",
      "Mexican Riviera",
      "Mexico",
      "Middle East",
      "Northern Europe",
      "Norway",
      "Pacific",
      "Pacific Coastal",
      "Panama Canal",
      "South America",
      "South Pacific",
      "Southern Europe",
      "Tasmania",
      "Transatlantic",
      "Western Mediterranean",
    ],
  },
  {
    slug: "celestyal-cruises",
    name: "Celestyal Cruises",
    offersHref: "https://thecruisenews.com/cruises/celestyal/",
    logoSrc: "/assets/logos/partner-cruise-lines/celestyal-cruises.svg",
    logoAlt: "Celestyal Cruises logo",
    logoClassName: "w-[7.5rem] sm:w-[8.2rem]",
    imageSrc: "/assets/images/cruise-lines/celestyal-cruises.png",
    imageAlt: "Celestyal Discovery at sea",
    detailImageSrc: "/assets/images/cruise-lines/celestyal-cruises-detail.jpg",
    detailImageAlt: "Celestyal Discovery at sea",
    description:
      "Celestyal Cruises embodies “authentically Greek” cruising, specialising in short, intensive voyages around the Aegean Sea’s islands, Turkey and the Eastern Mediterranean. Rebranded in 2014 from Louis Cruises, the line focuses on 3–7-night itineraries from Athens (Piraeus), blending Greek hospitality, included excursions and family-friendly onboard life with modernised ships.",
    descriptionParagraphs: [
      "Celestyal Cruises embodies “authentically Greek” cruising, specialising in short, intensive voyages around the Aegean Sea’s islands, Turkey and the Eastern Mediterranean. Rebranded in 2014 from Louis Cruises, the line focuses on 3–7-night itineraries from Athens (Piraeus), blending Greek hospitality, included excursions and family-friendly onboard life with modernised ships.",
      "The fleet—Celestyal Discovery (ex‑AIDAaura, joined 2024) and Celestyal Journey (ex‑AIDAcosma, joined 2023)—offers refurbished mid‑sized comfort for ~1,260 passengers, with balcony cabins, pools and Greek dining staples. Guests are diverse: Europeans, Americans and increasingly GCC families drawn to the value, culture and short lengths.",
      "Beyond Greece, Celestyal sails winter Gulf itineraries (Desert Days from Dubai/Doha) and Adriatic routes (Heavenly Adriatic to Croatia, Montenegro, Italy), plus Three Continents voyages touching Egypt, Israel and Cyprus. The 2026 programme expands Heavenly Adriatic and Idyllic Aegean sailings.",
    ],
    ships: ["Celestyal Discovery", "Celestyal Journey"],
    destinations: [
      "Arabian Gulf",
      "Eastern Mediterranean",
      "Mediterranean",
    ],
  },
  {
    slug: "royal-caribbean-international",
    name: "Royal Caribbean International",
    offersHref:
      "https://thecruisenews.com/cruises/royal-caribbean-international/",
    logoSrc: "/assets/logos/partner-cruise-lines/royal-caribbean-international.png",
    logoAlt: "Royal Caribbean International logo",
    logoClassName: "w-[6.65rem] sm:w-[7.25rem] h-[2.3rem] sm:h-[2.55rem]",
    imageSrc: "/assets/images/cruise-lines/royal-caribbean-international.jpg",
    imageAlt: "Legend of the Seas at sea",
    detailImageSrc: "/assets/images/cruise-lines/royal-caribbean-international-detail.jpg",
    detailImageAlt: "Icon of the Seas at sea",
    description:
      'Royal Caribbean International (RCI) is the world\'s largest cruise line by revenue and capacity, renowned for redefining the limits of what is possible at sea. Its fleet includes the world\'s largest cruise ships—the Icon and Oasis classes—which function as floating cities divided into distinct "neighbourhoods" like Central Park (with 20,000 real plants) and Thrill Island (home to the largest waterparks at sea).',
    descriptionParagraphs: [
      'Royal Caribbean International (RCI) is the world\'s largest cruise line by revenue and capacity, renowned for redefining the limits of what is possible at sea. Its fleet includes the world\'s largest cruise ships—the Icon and Oasis classes—which function as floating cities divided into distinct "neighbourhoods" like Central Park (with 20,000 real plants) and Thrill Island (home to the largest waterparks at sea).',
      'The brand ethos is "bold innovation." RCI consistently debuts industry-first features, such as the North Star observation capsule, robotic bartenders, and the AquaTheater high-diving shows. While the hardware is spectacular, the software caters to family fun: DreamWorks characters, Broadway musicals (like The Wizard of Oz and Grease), and massive kids’ clubs ensure entertainment for every demographic.',
      'Despite its mega-ship focus, RCI offers a tiered experience. The "Royal Suite Class" provides an ultra-luxury enclave with exclusive restaurants ("Coastal Kitchen"), sun decks, and "Royal Genies" (butlers), allowing affluent guests to bypass the crowds while enjoying the ship’s amenities. Operationally, RCI dominates the Caribbean but maintains a massive global footprint in Europe, Alaska, and Asia.',
    ],
    ships: [
      "Adventure of the Seas",
      "Allure of the Seas",
      "Anthem of the Seas",
      "Brilliance of the Seas",
      "Enchantment of the Seas",
      "Explorer of the Seas",
      "Freedom of the Seas",
      "Grandeur of the Seas",
      "Harmony of the Seas",
      "Icon of the Seas",
      "Independence of the Seas",
      "Jewel of the Seas",
      "Legend of the Seas",
      "Liberty of the Seas",
      "Mariner of the Seas",
      "Navigator of the Seas",
      "Oasis of the Seas",
      "Odyssey of the Seas",
      "Ovation of the Seas",
      "Quantum of the Seas",
      "Radiance of the Seas",
      "Rhapsody of the Seas",
      "Serenade of the Seas",
      "Spectrum of the Seas",
      "Symphony of the Seas",
      "Star of the Seas",
      "Utopia of the Seas",
      "Vision of the Seas",
      "Voyager of the Seas",
      "Wonder of the Seas",
    ],
    destinations: [
      "Alaska",
      "Asia and Asia Pacific",
      "Australia/New Zealand",
      "Bahamas",
      "Bermuda",
      "Canada / New England",
      "Caribbean",
      "Caribbean Eastern",
      "Caribbean Southern",
      "Caribbean Western",
      "Eastern Mediterranean",
      "Hawaii",
      "Mexico",
      "Northern Europe",
      "Pacific Coastal",
      "Panama Canal",
      "South Pacific",
      "Transatlantic",
      "Transpacific",
      "Western Europe",
      "Western Mediterranean",
    ],
  },
  {
    slug: "princess-cruises",
    name: "Princess Cruises",
    offersHref: "https://thecruisenews.com/cruises/princess/",
    logoSrc: "/assets/logos/partner-cruise-lines/princess-cruises.png",
    logoAlt: "Princess Cruises logo",
    logoClassName: "w-[8.45rem] sm:w-[9.15rem]",
    imageSrc: "/assets/images/cruise-lines/princess-cruises.jpg",
    imageAlt: "Princess Cruises ship at sea",
    detailImageSrc: "/assets/images/cruise-lines/princess-cruises.jpg",
    detailImageAlt: "Princess Cruises ship at sea",
    description:
      "Princess Cruises, founded in 1965 with a single ship, has grown into a global cruise line sailing to more than 345 destinations across all seven continents. The brand positions itself around personal, immersive travel, designing every detail to make guests feel valued and inspired. Today, the line operates 17 ships and is part of Carnival Corporation, with its headquarters in Fort Lauderdale.",
    descriptionParagraphs: [
      "Princess Cruises, founded in 1965 with a single ship, has grown into a global cruise line sailing to more than 345 destinations across all seven continents. The brand positions itself around personal, immersive travel, designing every detail to make guests feel valued and inspired. Today, the line operates 17 ships and is part of Carnival Corporation, with its headquarters in Fort Lauderdale.",
      "Princess is widely recognised as a pioneer in modern cruising, introducing innovations such as affordable balconies, flexible dining and even weddings at sea officiated by the ship’s captain. Its MedallionClass experience, built around a wearable Medallion device, enhances personalisation and convenience, while features like Movies Under the Stars have become signature elements of the brand.",
      "Life on board centres on destination immersion, thoughtful service and a blend of dining, entertainment and wellness experiences. From regional cuisine and Broadway-style shows to the adults‑only Sanctuary and the Princess Luxury Bed, the line focuses on comfort and connection. Consistently recognised with industry awards, Princess continues to emphasise heartfelt service and memorable journeys.",
    ],
    ships: [
      "Caribbean Princess",
      "Coral Princess",
      "Crown Princess",
      "Diamond Princess",
      "Discovery Princess",
      "Emerald Princess",
      "Enchanted Princess",
      "Grand Princess",
      "Island Princess",
      "Majestic Princess",
      "Regal Princess",
      "Royal Princess",
      "Ruby Princess",
      "Sapphire Princess",
      "Sky Princess",
      "Star Princess",
      "Sun Princess",
    ],
    destinations: [
      "Alaska",
      "Asia and Asia Pacific",
      "Australia",
      "Australia/New Zealand",
      "Bermuda",
      "British Isles",
      "Canada / New England",
      "Caribbean",
      "Caribbean Southern",
      "Eastern Europe",
      "Eastern Mediterranean",
      "Europe",
      "Hawaii",
      "Japan",
      "Mediterranean",
      "Mexico",
      "Northern Europe",
      "Pacific Coastal",
      "Panama Canal",
      "South America",
      "Southern Europe",
      "Transatlantic",
      "World Cruise",
    ],
  },
  {
    slug: "cunard",
    name: "Cunard",
    offersHref: "https://thecruisenews.com/cruises/cunard/",
    logoSrc: "/assets/logos/partner-cruise-lines/cunard.png",
    logoAlt: "Cunard logo",
    logoClassName: "w-[9rem] sm:w-[9.55rem]",
    imageSrc: "/assets/images/cruise-lines/cunard.webp",
    imageAlt: "Cunard ship at sea",
    detailImageSrc: "/assets/images/cruise-lines/cunard.webp",
    detailImageAlt: "Cunard ship at sea",
    description:
      "Cunard is synonymous with the \"Golden Age\" of ocean travel, maintaining a unique position in the industry as the operator of the world’s only true ocean liner, Queen Mary 2. Founded in 1840, the line blends deep-rooted British maritime heritage with modern luxury, famous for its \"White Star Service,\" formal Gala Evenings, and the sheer grandeur of its vessels. Today, Cunard balances this tradition with contemporary evolution, most notably with the 2024 launch of Queen Anne, which introduces updated design concepts while respecting the brand’s Art Deco legacy.",
    descriptionParagraphs: [
      "Cunard is synonymous with the \"Golden Age\" of ocean travel, maintaining a unique position in the industry as the operator of the world’s only true ocean liner, Queen Mary 2. Founded in 1840, the line blends deep-rooted British maritime heritage with modern luxury, famous for its \"White Star Service,\" formal Gala Evenings, and the sheer grandeur of its vessels. Today, Cunard balances this tradition with contemporary evolution, most notably with the 2024 launch of Queen Anne, which introduces updated design concepts while respecting the brand’s Art Deco legacy.",
      "The line is particularly known for its Transatlantic crossings and World Voyages. Unlike typical cruise lines that focus on “island hopping,” Cunard emphasises the journey itself, offering “sea days” rich with enrichment. This includes the renowned “Cunard Insights” programme featuring guest speakers from astronauts to authors, and arguably the finest ballroom dancing at sea in the Queens Room. The fleet offers a tiered “ship-within-a-ship” experience, where the category of stateroom determines the assigned dining room—Britannia, Princess Grill, or Queens Grill.",
      "Operations are worldwide but anchored by the iconic Southampton to New York route. Cunard also has a strong presence in Australia, Japan, and the Mediterranean. The atmosphere is dignified and ceremonious, appealing to travellers who appreciate dress codes, afternoon tea served by white-gloved waiters, and a sense of occasion that recalls the era of the great liners.",
    ],
    ships: [
      "Queen Elizabeth",
      "Queen Anne",
      "Queen Mary 2",
      "Queen Victoria",
    ],
    destinations: [
      "Africa",
      "Alaska",
      "Asia and Asia Pacific",
      "Australia/New Zealand",
      "Baltic Sea (Europe)",
      "Canada / New England",
      "Caribbean",
      "Eastern Europe",
      "Europe",
      "Mediterranean",
      "Northern Europe",
      "Panama Canal",
      "South America",
      "South Pacific",
      "Southern Europe",
      "Transatlantic",
      "Transpacific",
      "Western Europe",
      "World Cruise",
    ],
  },
  {
    slug: "p-and-o-cruises",
    name: "P&O Cruises",
    offersHref: "https://thecruisenews.com/cruises/poc/",
    logoSrc: "/assets/logos/partner-cruise-lines/p-and-o-cruises.png",
    logoAlt: "P&O Cruises logo",
    logoClassName: "w-[7.75rem] sm:w-[8.35rem] h-[2.75rem] sm:h-[3.15rem]",
    imageSrc: "/assets/images/cruise-lines/p-and-o-cruises.png",
    imageAlt: "P&O Cruises ship at sea",
    detailImageSrc: "/assets/images/cruise-lines/p-and-o-cruises.png",
    detailImageAlt: "P&O Cruises ship at sea",
    description:
      "P&O Cruises is firmly established as \"Britain's Favourite Cruise Line,\" offering a holiday experience uniquely tailored to British tastes. With a heritage tracing back to the 19th century, the line combines modern innovation with trusted traditions, such as Afternoon Tea and black-tie Gala Evenings. A key differentiator is its pricing model: guests pay in Pounds Sterling on board, avoiding exchange rate fluctuations, and gratuities are included in the fare.",
    descriptionParagraphs: [
      "P&O Cruises is firmly established as \"Britain's Favourite Cruise Line,\" offering a holiday experience uniquely tailored to British tastes. With a heritage tracing back to the 19th century, the line combines modern innovation with trusted traditions, such as Afternoon Tea and black-tie Gala Evenings. A key differentiator is its pricing model: guests pay in Pounds Sterling on board, avoiding exchange rate fluctuations, and gratuities are included in the fare.",
      "The fleet is diverse, ranging from the family-friendly Excel-class giants Arvia and Iona to the exclusively adult Arcadia and Aurora. The brand is renowned for its “Food Heroes” partnerships, bringing culinary legends like Marco Pierre White and Olly Smith on board for masterclasses and hosted dinners. Recent innovations include the “SkyDome” on the newest ships—a retractable glass-roofed entertainment venue that transforms from a pool deck by day to a performance space by night.",
      "Operations are primarily based out of Southampton, making P&O Cruises the leader in no-fly cruising for the UK market. The onboard atmosphere is sociable and relaxed, with entertainment that resonates with British audiences, from West End-style shows to cabaret and comedy. The line has also embraced contemporary trends with partnerships like the 2026 collaboration with DJ Pete Tong for exclusive Ibiza sets.",
    ],
    ships: [
      "Arvia",
      "Iona",
      "Britannia",
      "Azura",
      "Ventura",
      "Arcadia",
      "Aurora",
    ],
    destinations: [
      "Canada / New England",
      "Caribbean",
      "Europe",
      "Norway",
      "Western Europe",
      "World Cruise",
    ],
  },
  {
    slug: "oceania-cruises",
    name: "Oceania Cruises",
    offersHref: "https://thecruisenews.com/cruises/oceania-cruises/",
    logoSrc: "/assets/logos/partner-cruise-lines/oceania-cruises.png",
    logoAlt: "Oceania Cruises logo",
    logoClassName: "w-[8.9rem] sm:w-[9.6rem]",
    imageSrc: "/assets/images/cruise-lines/oceania-cruises.jpg",
    imageAlt: "Oceania Cruises ship at sea",
    detailImageSrc: "/assets/images/cruise-lines/oceania-cruises.jpg",
    detailImageAlt: "Oceania Cruises ship at sea",
    description:
      "Oceania Cruises is renowned as the world's leading culinary- and destination-focused upper-premium line, offering intimate ships that prioritise exquisite dining, immersive itineraries, and personalised service for discerning travellers. Part of Norwegian Cruise Line Holdings since 2014, it sails exclusively to 600+ marquee and boutique ports across 100 countries, spending 30–50% more time in port than mainstream lines, including frequent overnights for deeper exploration.",
    descriptionParagraphs: [
      "Oceania Cruises is renowned as the world's leading culinary- and destination-focused upper-premium line, offering intimate ships that prioritise exquisite dining, immersive itineraries, and personalised service for discerning travellers. Part of Norwegian Cruise Line Holdings since 2014, it sails exclusively to 600+ marquee and boutique ports across 100 countries, spending 30–50% more time in port than mainstream lines, including frequent overnights for deeper exploration.",
      "The line distinguishes itself through “The Finest Cuisine at Sea,” masterminded by Chef Jacques Pépin, with all main dining venues complimentary and featuring regionally inspired menus using the freshest ingredients. Its small ships (684–1,250 guests) deliver a residential feel with high space ratios, while “Your World Included” packages bundle Wi-Fi, drinks, speciality coffees, and laundry. From January 2026, Oceania transitions to adults-only (18+) sailings, enhancing its sophisticated appeal for mature couples and solo adventurers.",
      "Operations emphasise world-spanning voyages from 7 to 200+ days, including 17 Grand Voyages and Around the World cruises aboard boutique ships like Nautica, Regatta, and Sirena. The refined atmosphere blends genuine hospitality with enrichment lectures, cooking demonstrations, and wellness at Aquamar Spa + Vitality Center.",
    ],
    ships: [
      "Allura",
      "Insignia",
      "Marina",
      "Nautica",
      "Regatta",
      "Riviera",
      "Sirena",
      "Vista",
    ],
    destinations: [
      "Africa",
      "Alaska",
      "Asia and Asia Pacific",
      "Australasia",
      "Australia/New Zealand",
      "Baltic Sea (Europe)",
      "Canada / New England",
      "Canary Islands",
      "Caribbean",
      "Caribbean Eastern",
      "Caribbean Western",
      "Eastern Europe",
      "Eastern Mediterranean",
      "Europe",
      "Greenland",
      "Hawaii",
      "Japan",
      "Mediterranean",
      "New Zealand",
      "Northern Europe",
      "Pacific",
      "Panama Canal",
      "Repositioning",
      "South America",
      "South Pacific",
      "Southeast Asia",
      "Southern Europe",
      "Transatlantic",
      "Transpacific",
      "Western Mediterranean",
      "World Cruise",
    ],
  },
  {
    slug: "regent-seven-seas-cruises",
    name: "Regent Seven Seas Cruises",
    offersHref:
      "https://thecruisenews.com/cruises/regent-seven-seas-cruises/",
    logoSrc:
      "/assets/logos/partner-cruise-lines/regent-seven-seas-cruises.png",
    logoAlt: "Regent Seven Seas Cruises logo",
    logoClassName: "w-[8.65rem] sm:w-[9.3rem] h-[2.4rem] sm:h-[2.65rem]",
    imageSrc: "/assets/images/cruise-lines/regent-seven-seas-cruises.jpg",
    imageAlt: "Regent Seven Seas Cruises ship at sea",
    detailImageSrc: "/assets/images/cruise-lines/regent-seven-seas-cruises.jpg",
    detailImageAlt: "Regent Seven Seas Cruises ship at sea",
    description:
      "Regent Seven Seas Cruises delivers the most inclusive ultra-luxury experience at sea, where every voyage includes unlimited shore excursions, business-class air, premium beverages, gourmet dining, Wi-Fi, laundry, and gratuities across all-suite ships designed for effortless sophistication. Evolved from Radisson Seven Seas since 1992, it now sails The World's Most Luxurious Fleet® of six Explorer-class vessels plus smaller R-class ships, offering unrivalled space ratios and butler service for every guest.",
    descriptionParagraphs: [
      "Regent Seven Seas Cruises delivers the most inclusive ultra-luxury experience at sea, where every voyage includes unlimited shore excursions, business-class air, premium beverages, gourmet dining, Wi-Fi, laundry, and gratuities across all-suite ships designed for effortless sophistication. Evolved from Radisson Seven Seas since 1992, it now sails The World's Most Luxurious Fleet® of six Explorer-class vessels plus smaller R-class ships, offering unrivalled space ratios and butler service for every guest.",
      "The line pioneered all-inclusive luxury with business-class flights and unlimited excursions at every port, enabling truly immersive travel to 550+ destinations worldwide. Regent’s intimate scale (375–750 guests) ensures personalised Heartfelt Hospitality™, while palatial Regent Suites and expansive public spaces create residential elegance. Culinary excellence spans 11 complimentary venues, from steakhouses to French tasting menus, complemented by enrichment lectures and live entertainment.",
      "Operations encompass immersive overnight sailings, Grand Voyages spanning continents, and the 154-night 2026 World Cruise visiting 70+ ports. The refined atmosphere appeals to affluent couples and solo travellers who value space, service, and seamless sophistication over onboard spectacle.",
    ],
    ships: [
      "Seven Seas Explorer",
      "Seven Seas Grandeur",
      "Seven Seas Mariner",
      "Seven Seas Navigator",
      "Seven Seas Prestige (2026)",
      "Seven Seas Splendor",
      "Seven Seas Voyager",
    ],
    destinations: [
      "Africa",
      "Alaska",
      "Asia and Asia Pacific",
      "Australia/New Zealand",
      "Canada / New England",
      "Caribbean Eastern",
      "Caribbean Western",
      "Eastern Mediterranean",
      "Indian Ocean",
      "Japan",
      "Mexican Riviera",
      "Northern Europe",
      "Pacific",
      "Panama Canal",
      "South America",
      "Southeast Asia",
      "Transatlantic",
      "Western Europe",
      "Western Mediterranean",
      "World Cruise",
    ],
  },
  {
    slug: "celebrity-cruises",
    name: "Celebrity Cruises",
    offersHref: "https://thecruisenews.com/cruises/celebrity/",
    logoSrc: "/assets/logos/partner-cruise-lines/celebrity-cruises.png",
    logoAlt: "Celebrity Cruises logo",
    logoClassName: "w-[8.95rem] sm:w-[9.55rem]",
    imageSrc: "/assets/images/cruise-lines/celebrity-cruises.jpg",
    imageAlt: "Celebrity Cruises ship at sea",
    detailImageSrc: "/assets/images/cruise-lines/celebrity-cruises.jpg",
    detailImageAlt: "Celebrity Cruises ship at sea",
    description:
      'Celebrity Cruises is the premium brand within Royal Caribbean Group, positioned as "relaxed luxury" for guests who want an upscale experience without the formality of traditional luxury lines. Established in 1988 in Greece and acquired by Royal Caribbean in 1997, the line is known for clean, modern design, strong culinary programmes, and destination‑focused itineraries, particularly in Europe and Alaska. The fleet is mid‑sized by contemporary standards, allowing for a quieter onboard atmosphere and access to a wide array of ports.',
    descriptionParagraphs: [
      'Celebrity Cruises is the premium brand within Royal Caribbean Group, positioned as "relaxed luxury" for guests who want an upscale experience without the formality of traditional luxury lines. Established in 1988 in Greece and acquired by Royal Caribbean in 1997, the line is known for clean, modern design, strong culinary programmes, and destination‑focused itineraries, particularly in Europe and Alaska. The fleet is mid‑sized by contemporary standards, allowing for a quieter onboard atmosphere and access to a wide array of ports.',
      "The line is especially recognised for its Edge‑series ships, which introduced striking architectural features such as the outward‑facing Resort Deck, Infinite Veranda staterooms, and the cantilevered multi‑use Magic Carpet platform. Celebrity is often cited as a leader in design and art, with extensive curated collections and stylish public spaces across the fleet. Its typical guest is a couple or group of friends—often well‑travelled professionals—who value quality dining, design, and service over high‑octane top‑deck attractions.",
      "Operations are global, with a strong presence in Europe (including extensive ex‑UK sailings), Alaska, the Caribbean, and the Galápagos (via small expedition ships). The onboard ambience is cosmopolitan but calm: think craft cocktails, jazz and acoustic sets, and destination lectures rather than waterparks and rollercoasters. Celebrity has also invested heavily in its “Always Included” style pricing (on many markets), bundling Wi‑Fi, drinks, and service charges into a simple premium package.",
    ],
    ships: [
      "Celebrity Apex",
      "Celebrity Ascent",
      "Celebrity Beyond",
      "Celebrity Constellation",
      "Celebrity Eclipse",
      "Celebrity Edge",
      "Celebrity Equinox",
      "Celebrity Infinity",
      "Celebrity Millennium",
      "Celebrity Reflection",
      "Celebrity Silhouette",
      "Celebrity Solstice",
      "Celebrity Summit",
      "Celebrity Xcel",
      "Celebrity Xcite (on order for 2028)",
    ],
    destinations: [
      "Alaska",
      "Asia and Asia Pacific",
      "Australia/New Zealand",
      "Bahamas",
      "Bermuda",
      "Canada / New England",
      "Caribbean",
      "Caribbean Eastern",
      "Caribbean Southern",
      "Caribbean Western",
      "Eastern Europe",
      "Eastern Mediterranean",
      "Europe",
      "Galapagos",
      "Greenland",
      "Hawaii",
      "Iceland",
      "Japan",
      "Northern Europe",
      "Pacific Coastal",
      "Panama Canal",
      "South America",
      "Southeast Asia",
      "Transatlantic",
      "Transpacific",
      "Western Europe",
      "Western Mediterranean",
    ],
  },
  {
    slug: "carnival-cruise-line",
    name: "Carnival Cruise Line",
    offersHref: "https://thecruisenews.com/cruises/carnival/",
    logoSrc: "/assets/logos/partner-cruise-lines/carnival-cruise-line.png",
    logoAlt: "Carnival Cruise Line logo",
    logoClassName: "w-[8.85rem] sm:w-[9.45rem]",
    imageSrc: "/assets/images/cruise-lines/carnival-cruise-line.webp",
    imageAlt: "Carnival Cruise Line ship at sea",
    detailImageSrc: "/assets/images/cruise-lines/carnival-cruise-line.webp",
    detailImageAlt: "Carnival Cruise Line ship at sea",
    description:
      "Carnival Cruise Line is one of the world’s largest and best-known cruise brands, positioned firmly as the “Fun Ship” choice for value-minded holidaymakers who prioritise lively entertainment and a casual, social atmosphere. It focuses on big-ship thrills, upbeat décor, and approachable service, designed to feel more like a floating resort than a traditional ocean liner. The line targets families, younger couples, and groups of friends who want an informal, activity-packed break with plenty of dining options and nightlife.",
    descriptionParagraphs: [
      "Carnival Cruise Line is one of the world’s largest and best-known cruise brands, positioned firmly as the “Fun Ship” choice for value-minded holidaymakers who prioritise lively entertainment and a casual, social atmosphere. It focuses on big-ship thrills, upbeat décor, and approachable service, designed to feel more like a floating resort than a traditional ocean liner. The line targets families, younger couples, and groups of friends who want an informal, activity-packed break with plenty of dining options and nightlife.",
      "Carnival is particularly recognised for bringing theme-park style attractions to sea, including top-deck waterparks, roller-coaster-style rides on select ships, and large outdoor fun zones. Over the past decade it has been rolling out newer, more efficient vessels (such as the Excel-class, powered by LNG) with expanded open-air spaces and dedicated zones for kids, teens, and adults-only relaxation. The onboard culture is unpretentious and high-energy, with comedy clubs, deck parties, and game shows forming a core part of the evening programme.",
      "Operations are focused primarily on North America, with a heavy presence in Florida and Gulf Coast homeports, plus additional sailings from the US West Coast and seasonal deployments further afield. The brand’s model of frequent, shorter itineraries makes it a popular choice for first-time cruisers and repeat guests looking for an easy, fly-or-drive getaway. While firmly mainstream, Carnival has also invested in upgraded dining programmes, new bars and lounges, and expanded adults-only retreats to appeal to guests seeking a better balance of fun and relaxation.",
    ],
    ships: [
      "Carnival Adventure",
      "Carnival Breeze",
      "Carnival Celebration",
      "Carnival Conquest",
      "Carnival Dream",
      "Carnival Elation",
      "Carnival Encounter",
      "Carnival Festivale",
      "Carnival Freedom",
      "Carnival Firenze",
      "Carnival Glory",
      "Carnival Horizon",
      "Carnival Jubilee",
      "Carnival Legend",
      "Carnival Liberty",
      "Carnival Luminosa",
      "Carnival Magic",
      "Carnival Miracle",
      "Carnival Panorama",
      "Carnival Paradise",
      "Carnival Pride",
      "Carnival Radiance",
      "Carnival Spirit",
      "Carnival Splendor",
      "Carnival Sunrise",
      "Carnival Sunshine",
      "Carnival Valor",
      "Carnival Venezia",
      "Carnival Vista",
      "Mardi Gras",
    ],
    destinations: [
      "Alaska",
      "Asia and Asia Pacific",
      "Australia",
      "Bahamas",
      "Baja Mexico",
      "Baltic Sea (Europe)",
      "Bermuda",
      "British Isles",
      "Canada / New England",
      "Caribbean",
      "Caribbean Eastern",
      "Caribbean Southern",
      "Caribbean Western",
      "Europe",
      "Fiji",
      "Hawaii",
      "Mediterranean",
      "Mexican Riviera",
      "New Zealand",
      "Northern Europe",
      "Panama Canal",
      "South America",
      "South Pacific",
      "Southeast Asia",
      "Southern Europe",
      "Tasmania",
      "Transatlantic",
      "Transpacific",
      "Vanuatu",
    ],
  },
  {
    slug: "ama-waterways",
    name: "AmaWaterways",
    offersHref: "https://thecruisenews.com/cruises/amawaterways/",
    logoSrc: "/assets/logos/partner-cruise-lines/ama-waterways.png",
    logoAlt: "AmaWaterways logo",
    logoClassName: "w-[9.75rem] sm:w-[10.5rem] h-[2.2rem] sm:h-[2.45rem]",
    imageSrc: "/assets/images/cruise-lines/ama-waterways.jpg",
    imageAlt: "AmaWaterways ship at sea",
    detailImageSrc: "/assets/images/cruise-lines/ama-waterways.jpg",
    detailImageAlt: "AmaWaterways ship at sea",
    description:
      'AmaWaterways is widely regarded as the innovator of modern luxury river cruising, founded in 2002 by industry pioneers Rudi Schreiner, Kristin Karst, and Jimmy Murphy. The line distinguishes itself through a philosophy of "The Heart of the River," prioritising warm, personalised service and ship design that enhances the guest experience. It was the first river cruise line to introduce "Twin Balcony" staterooms (featuring both a French and outside balcony) and the first to carry a fleet of complimentary bicycles on board for active exploration.',
    descriptionParagraphs: [
      'AmaWaterways is widely regarded as the innovator of modern luxury river cruising, founded in 2002 by industry pioneers Rudi Schreiner, Kristin Karst, and Jimmy Murphy. The line distinguishes itself through a philosophy of "The Heart of the River," prioritising warm, personalised service and ship design that enhances the guest experience. It was the first river cruise line to introduce "Twin Balcony" staterooms (featuring both a French and outside balcony) and the first to carry a fleet of complimentary bicycles on board for active exploration.',
      "Today, AmaWaterways operates the most diverse and modern fleet on the world’s waterways. This includes the revolutionary AmaMagna—twice the width of traditional river ships—which redefines space and luxury on the Danube. The line is also a leader in wellness, employing dedicated “Wellness Hosts” on every ship to lead daily classes, and offers an extensive choice of included shore excursions in every port, catering to “Gentle,” “Regular,” and “Active” walking paces.",
    ],
    ships: [
      "AmaBella",
      "AmaCello",
      "AmaCerto",
      "AmaDahlia",
      "AmaDante",
      "AmaDara",
      "AmaDolce",
      "AmaDouro",
      "AmaFiora",
      "AmaKaia",
      "AmaKaterina",
      "AmaKristina",
      "AmaLea",
      "AmaLilia",
      "AmaLucia",
      "AmaLyra",
      "AmaMagdalena",
      "AmaMagna",
      "AmaMaya",
      "AmaMelodia",
      "AmaMora",
      "AmaPrima",
      "AmaRudi",
      "AmaReina",
      "AmaSerena",
      "AmaSiena",
      "AmaSintra",
      "AmaSofia",
      "AmaSonata",
      "AmaStella",
      "AmaVenita",
      "AmaVerde",
      "AmaVida",
      "AmaViola",
      "Zambezi Queen",
    ],
    destinations: [
      "Africa",
      "Asia and Asia Pacific",
      "Europe",
      "South America",
      "Southeast Asia",
      "Danube (Europe)",
      "Dordogne (Europe)",
      "Douro (Europe)",
      "Dutchand Belgian Waterways (Europe)",
      "Garonne (Europe)",
      "Ha Long Bay (Vietnam)",
      "Magdalena River",
      "Main (Europe)",
      "Mekong (Asia)",
      "Moselle (Europe)",
      "Rhine (Europe)",
      "Rhone (Europe)",
      "Saone (Europe)",
      "Seine (Europe)",
    ],
  },
  {
    slug: "avalon-waterways",
    name: "Avalon Waterways",
    offersHref: "https://thecruisenews.com/cruises/avalon-waterways/",
    logoSrc: "/assets/logos/partner-cruise-lines/avalon-waterways.png",
    logoAlt: "Avalon Waterways logo",
    logoClassName: "w-[9.35rem] sm:w-[9.95rem] h-[2.2rem] sm:h-[2.45rem]",
    imageSrc: "/assets/images/cruise-lines/avalon-waterways.jpg",
    imageAlt: "Avalon Waterways ship at sea",
    detailImageSrc: "/assets/images/cruise-lines/avalon-waterways.jpg",
    detailImageAlt: "Avalon Waterways ship at sea",
    description:
      "Avalon Waterways revolutionised river cruising in 2011 with the launch of Panorama, the industry's first Suite Ship featuring wall-to-wall, floor-to-ceiling windows and beds facing outward—innovations now widely copied but first pioneered by Avalon. The line's Suite Ships dedicate 80% of staterooms to Panorama Suites, approximately one-third larger than competitors, with unique slide-open windows creating open-air balconies.",
    descriptionParagraphs: [
      "Avalon Waterways revolutionised river cruising in 2011 with the launch of Panorama, the industry's first Suite Ship featuring wall-to-wall, floor-to-ceiling windows and beds facing outward—innovations now widely copied but first pioneered by Avalon. The line's Suite Ships dedicate 80% of staterooms to Panorama Suites, approximately one-third larger than competitors, with unique slide-open windows creating open-air balconies.",
      "The Avalon philosophy centres on “Cruising as you want it”—flexible dining times, à la carte menus, and the industry-leading Choice excursions programme offering Classic, Discovery, and Active options in every port. This appeals to younger, more independent travellers (average age mid-50s, younger than luxury lines) who reject rigid schedules.",
      "In 2024–2026, Avalon launched a comprehensive fleet-wide refresh installing Starlink high-speed internet, redesigned Sky Decks, upgraded fitness centres with Kinesis machines, and 15 new bicycles plus 4 e-bikes per ship—maintaining its position as the choice for active, design-forward river cruising.",
    ],
    ships: [
      "Avalon Artistry II",
      "Avalon Alegria",
      "Avalon Envision",
      "Avalon Expression",
      "Avalon Illumination",
      "Avalon Imagery II",
      "Avalon Impression",
      "Avalon Panorama",
      "Avalon Passion",
      "Avalon Poetry II",
      "Avalon Saigon",
      "Avalon Siem Reap",
      "Avalon Tapestry II",
      "Avalon Tranquility II",
      "Avalon View",
      "Avalon Visionary",
      "Avalon Vista",
      "Delfin III (Charter)",
      "MS Farah (Charter)",
      "Ganges Voyager (Charter)",
      "Treasure of Galapagos (Charter)",
    ],
    destinations: [
      "Africa",
      "Asia and Asia Pacific",
      "Eastern Europe",
      "Europe",
      "Middle East",
      "Northern Europe",
      "South America",
      "Southeast Asia",
      "Western Europe",
      "Amazon River (South America)",
      "Danube (Europe)",
      "Dordogne (Europe)",
      "Douro (Europe)",
      "Dutchand Belgian Waterways (Europe)",
      "Garonne (Europe)",
      "Gironde (Europe)",
      "Main (Europe)",
      "Mekong (Asia)",
      "Moselle (Europe)",
      "Nile (Africa)",
      "Rhine (Europe)",
      "Rhone (Europe)",
      "Saone (Europe)",
      "Seine (Europe)",
    ],
  },
] as const;

export function getCruiseLineBySlug(slug: string): CruiseLine | undefined {
  return cruiseLines.find((line) => line.slug === slug);
}

export const partnerCruiseLines = cruiseLines.map((line) => ({
  name: line.name,
  href: `/cruise-lines/${line.slug}`,
  logoSrc: line.logoSrc,
  logoAlt: line.logoAlt,
  logoClassName: line.logoClassName,
}));

export const homeHeroSubtitle =
  "Exclusive discounted cruise fares for airline, travel, tourism and hospitality professionals across the Middle East.";

export const programmeSteps = [
  "Register with your business email for verification",
  "Get approved",
  "Log in and access interline rates",
  "Book with your discount applied",
] as const;

export const eligibleOrganisations = [
  "Airlines",
  "Airports and aviation services",
  "Travel agencies and tour operators",
  "Hotels and hospitality groups",
  "Tourism boards and destination management companies",
  "Cargo, charter and GSA representatives",
  "Ground handling and air services",
] as const;

export const expandedEligibleProfessions = [
  "Airlines",
  "Airports and aviation services",
  "Travel agencies and tour operators",
  "Hotels and hospitality groups",
  "Tourism boards and destination management companies",
  "Cargo, charter and GSA representatives",
  "Ground handling and air services",
] as const;

export const familyEligibility = [
  "Spouse",
  "Children",
  "Parents",
  "Friends",
] as const;

export const currentCruiseOffers = [
  "Mediterranean sailings with leading cruise brands",
  "Arabian Gulf voyages closer to home",
  "European and island itineraries with added benefits",
] as const;

export const homeIntroduction = [
  "For the ones who keep travel moving, this one’s for you.",
  "You help people turn travel dreams into memories. Whether you work across an airline, support travellers on the ground, welcome guests in hotels or shape the experiences that bring destinations to life, you play a part in creating holidays people never forget. You understand the excitement of a long awaited break, the joy of discovering somewhere new and the magic of a journey that unfolds exactly as it should.",
  "And because you spend so much of your energy making travel seamless for others, you deserve a holiday that feels just as effortless for you. A chance to step away from the pace of daily operations and into a world where everything is taken care of. Where you can unpack once, wake up somewhere new each morning, and enjoy the perfect blend of relaxation, entertainment and discovery that only a cruise can offer.",
  "That is exactly what Interline Cruises Middle East brings to you.",
  "A dedicated space where the travel community can access exclusive, verified interline rates on cruise holidays. Once you are registered and verified, you can browse offers, explore ships and destinations, and book directly with your industry discount already applied.",
  "These fares are not public. They exist as a quiet thank you, giving you the chance to enjoy a complete holiday experience that is as rewarding as it is relaxing.",
] as const;

export const whoWeAreParagraphs = [
  "Interline Cruises Middle East is the region’s first platform created specifically for the travel community. A place designed for those who live and breathe travel, where the cruise holidays you often recommend to others are now reserved for you.",
  "As a registered member, you can explore cruise lines and book your next holiday directly through a secure platform with your exclusive industry discount already included.",
] as const;

export const whyChooseUsParagraphs = [
  "When you work in travel, you are used to being the one who makes journeys possible. Here, you are the one being looked after. Interline Cruises Middle East was built exclusively for the region’s travel professionals, offering a trusted space where your industry status unlocks real value.",
  "Your verification protects genuine industry benefits, ensuring these fares remain reserved for those who have earned them. And because we partner directly with global cruise brands, you gain access to authentic interline discounts with no hidden fees or third party markups. And yes, your family and friends get to enjoy the perks too.",
  "One platform, one login, and a world of cruise holidays ready to explore.",
] as const;

export const homeEligibilityParagraph =
  "If you are part of the Middle East travel or hospitality ecosystem, you qualify for interline access once verified. Your role, your experience and your contribution to the industry is what opens the door.";

export const homeFamilyEligibilityParagraph =
  "Your interline benefits extend beyond you. Your spouse, children, parents and friends can sail using your industry access. Whether you are travelling together or gifting them a well-deserved break, your verification unlocks exclusive cruise savings for the people you care about.";

export const homeEligibilityClosing =
  "Join Interline Cruises Middle East and unlock exclusive cruise rates reserved for the travel industry.";

export const homePartnerCruiseLinesParagraphs = [
  "Cruising is one of the easiest ways to switch off and truly unwind. With your interline access, it becomes even more accessible, whether you are looking for a short escape or a longer voyage across continents.",
  "You will find offers across a wide range of the world’s most loved cruise lines, from contemporary and premium brands to luxury, river, expedition and niche experiences. Each one brings something different to the journey, and all of them are now within reach.",
  "All displayed fares already include your interline benefit. Additional promotions may apply where available. New offers are added regularly across destinations, seasons and cruise lines. Your next holiday might already be waiting.",
] as const;

export const partnerCruiseLinesSummary =
  "Norwegian Cruise Line, Celestyal Cruises, Royal Caribbean International, Princess Cruises, Cunard, P&O Cruises, Oceania Cruises, Regent Seven Seas Cruises, Celebrity Cruises, Carnival Cruise Line, AmaWaterways, Avalon Waterways and more.";

export type FaqItem = {
  question: string;
  paragraphs: readonly string[];
  listItems?: readonly string[];
  afterListParagraphs?: readonly string[];
};

export const faqItems: readonly FaqItem[] = [
  {
    question: "What are interline cruise rates?",
    paragraphs: [
      "Interline cruise rates are exclusive, privately offered fares that cruise lines reserve for professionals working in the airline, travel, tourism and hospitality industry.",
      "These fares are not available to the public.",
      "They are part of long standing industry partnerships that recognise the people who help keep global travel moving.",
      "Through Interline Cruises Middle East, eligible members can access these special cruise offers and book holidays at preferred industry only rates.",
    ],
  },
  {
    question: "Who qualifies for interline cruise rates?",
    paragraphs: [
      "Interline cruise rates are available to current employees working in airline, travel, tourism or hospitality organisations based in the Middle East.",
      "This includes professionals working across airlines, airports, travel agencies, tour operators, hotels, tourism boards and related organisations within the region.",
    ],
  },
  {
    question: "Can former travel industry employees apply?",
    paragraphs: [
      "No. Interline Cruises Middle East is currently available only to active, full time employees working in eligible organisations within the Middle East.",
    ],
  },
  {
    question: "Can family members travel at interline rates?",
    paragraphs: [
      "Yes. Your interline benefits extend to your spouse, children, parents and friends. They can travel with you, or you can book a cruise for them through your verified account.",
      "Your verification unlocks access for the people you care about.",
    ],
  },
  {
    question: "Do I need to prove my employment?",
    paragraphs: [
      "Yes. Verification is required to ensure that interline benefits remain exclusive to the travel industry.",
      "You can verify your eligibility using your business email address or by providing official proof of employment, such as a staff ID or company documentation.",
      "This helps maintain a secure and trusted platform for all members.",
    ],
  },
  {
    question: "Do I need to work in the Middle East to qualify?",
    paragraphs: [
      "Yes. You must be currently employed by an airline, travel, tourism or hospitality organisation based in the Middle East.",
      "These interline rates are specifically designed for professionals working within the region.",
    ],
  },
  {
    question: "Are interline fares lower than public cruise prices?",
    paragraphs: [
      "Interline fares are privately negotiated and often lower than publicly available cruise prices.",
      "They may also include access to selected promotions that are not offered to general travellers.",
    ],
  },
  {
    question: "Is there a cost to register?",
    paragraphs: [
      "No. Registration is free for eligible travel and hospitality professionals.",
      "The platform is designed as an industry benefit, giving you access to exclusive cruise offers.",
    ],
  },
  {
    question: "Can I book cruises directly through the website?",
    paragraphs: [
      "Yes. Once logged in, you can browse available cruise offers and complete your booking directly through the platform.",
      "Your interline discount is automatically applied, so you can book with confidence",
    ],
  },
];

export const privacyContactEmail = "privacy@interlinecruisesme.com";
